class DeviseCreateUsers < ActiveRecord::Migration[6.1]
  def up
    execute(<<~SQL)
      create extension if not exists "citext";
      create extension if not exists "uuid-ossp";

      create table users (
        id bigint generated by default as identity primary key,
        email citext unique not null,
        encrypted_password text not null,
        reset_password_token text unique,
        reset_password_sent_at timestamptz,
        super_magic_token uuid unique,
        super_magic_token_sent_at timestamptz,
        super_magic_token_opened_at timestamptz,
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now()
      );
    SQL
  end

  def down
    execute(<<~SQL)
      drop table users;
      drop extension if exists "uuid-ossp";
      drop extension if exists "citext";
    SQL
  end
end
